import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    marginTop: Platform.OS === 'ios' ? 50 : 20,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flex: 1,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  locationIconContainer: {
    marginRight: 8,
  },
  locationText: {
    flex: 1,
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  cartButton: {
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    padding: 10,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  cartBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#2EC4B6',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    color: '#000000',
    fontSize: 12,
    fontWeight: 'bold',
  },
  welcomeSection: {
    marginTop: 8,
    marginBottom: 24,
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  welcomeSubText: {
    fontSize: 16,
    color: '#CCCCCC',
    marginTop: 4,
  },
  searchWrapper: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  searchIconContainer: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    color: '#FFFFFF',
  },
  clearButton: {
    padding: 4,
  },
  fymButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2EC4B6',
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  fymButtonText: {
    marginLeft: 4,
    color: '#000000',
    fontWeight: 'bold',
  },
  medicineResultsContainer: {
    backgroundColor: '#2EC4B6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  resultsHeader: {
    marginBottom: 16,
  },
  resultsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  resultsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
  },
  cutButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 20,
    padding: 4,
  },
  resultsCount: {
    fontSize: 14,
    color: '#000000',
    marginTop: 4,
    opacity: 0.7,
  },
  medicineList: {
    maxHeight: 300,
  },
  medicineItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  medicineInfo: {
    flex: 1,
  },
  medicineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  medicineName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  stockBadge: {
    backgroundColor: '#2EC4B6',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  outOfStockBadge: {
    backgroundColor: '#FF6B6B',
  },
  stockText: {
    fontSize: 12,
    color: '#000000',
    fontWeight: 'bold',
  },
  outOfStockText: {
    color: '#FFFFFF',
  },
  manufacturerText: {
    fontSize: 14,
    color: '#CCCCCC',
    marginTop: 2,
  },
  medicineDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  categoryTag: {
    backgroundColor: '#2EC4B6',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  categoryText: {
    fontSize: 12,
    color: '#000000',
  },
  priceText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2EC4B6',
  },
  addToCartButton: {
    marginLeft: 12,
  },
  disabledButton: {
    opacity: 0.5,
  },
  noResultsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  noResultsText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
    marginTop: 16,
  },
  noResultsSubText: {
    fontSize: 14,
    color: '#000000',
    marginTop: 4,
    opacity: 0.7,
  },
  cardsSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bigCard: {
    width: '48%',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  cardIconContainer: {
    alignItems: 'center',
    marginBottom: 12,
  },
  cardIconBg: {
    backgroundColor: '#2EC4B6',
    borderRadius: 20,
    padding: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  cardSubText: {
    fontSize: 12,
    color: '#CCCCCC',
    marginBottom: 12,
  },
  prescriptionPreview: {
    width: '100%',
    height: 80,
    borderRadius: 8,
    marginBottom: 12,
  },
  cardAction: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardActionText: {
    fontSize: 14,
    color: '#2EC4B6',
    fontWeight: 'bold',
    marginRight: 4,
  },
  quickActionsSection: {
    marginBottom: 24,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  quickActionCard: {
    width: '23%',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  quickActionIcon: {
    backgroundColor: '#2EC4B6',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 12,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  mapContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  map: {
    flex: 1,
  },
  mapControls: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  mapButtonText: {
    marginLeft: 8,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  confirmButton: {
    backgroundColor: '#2EC4B6',
    borderColor: '#2EC4B6',
  },
  confirmButtonText: {
    color: '#000000',
    fontWeight: 'bold',
  },
  errorBanner: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: '#FF6B6B',
    borderRadius: 8,
    padding: 12,
  },
  errorText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: '600',
  },
  cartModal: {
    flex: 1,
    backgroundColor: '#000000',
  },
  cartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2EC4B6',
    marginTop: Platform.OS === 'ios' ? 40 : 0,
  },
  cartTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  closeCartButton: {
    padding: 4,
  },
  emptyCartContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  emptyCartText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 16,
  },
  emptyCartSubText: {
    fontSize: 14,
    color: '#CCCCCC',
    marginTop: 4,
  },
  continueShopping: {
    marginTop: 24,
    backgroundColor: '#2EC4B6',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  continueShoppingText: {
    color: '#000000',
    fontWeight: 'bold',
  },
  cartItemsList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  cartItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2EC4B6',
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  cartItemManufacturer: {
    fontSize: 14,
    color: '#CCCCCC',
    marginTop: 2,
  },
  cartItemPrice: {
    fontSize: 14,
    color: '#CCCCCC',
    marginTop: 4,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
  },
  quantityButton: {
    padding: 4,
  },
  quantityText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginHorizontal: 8,
  },
  cartItemTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2EC4B6',
    minWidth: 60,
    textAlign: 'right',
  },
  cartFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#2EC4B6',
  },
  totalSection: {
    marginBottom: 16,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  totalLabel: {
    fontSize: 14,
    color: '#CCCCCC',
  },
  totalValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  deliveryFree: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2EC4B6',
  },
  grandTotalRow: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#2EC4B6',
  },
  grandTotalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  grandTotalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2EC4B6',
  },
  placeOrderButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2EC4B6',
    borderRadius: 8,
    padding: 16,
  },
  placeOrderText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
    marginLeft: 8,
  },
  markerContainer: {
    alignItems: 'center',
  },
  markerPin: {
    backgroundColor: 'white',
    padding: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FF6B6B',
  },
  markerPointer: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 16,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FF6B6B',
    marginTop: -4,
  },
  userMarker: {
    backgroundColor: 'white',
    padding: 5,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#2EC4B6',
  },
  sellerMarker: {
    backgroundColor: 'white',
    padding: 5,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FF6B6B',
  },
  sellersListContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    maxHeight: '50%',
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  sellersListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sellersListTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  sellersList: {
    marginBottom: 16,
  },
  sellerCard: {
    backgroundColor: '#000000',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2EC4B6',
  },
  sellerInfo: {
    flex: 1,
  },
  sellerName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  sellerDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  sellerRating: {
    marginLeft: 4,
    marginRight: 12,
    color: '#FFFFFF',
  },
  sellerDistance: {
    color: '#CCCCCC',
  },
  sellerAddress: {
    color: '#CCCCCC',
    fontSize: 14,
  },
  selectSellerButton: {
    backgroundColor: '#2EC4B6',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  selectSellerText: {
    color: '#000000',
    fontWeight: 'bold',
  },
  confirmSellerButton: {
    backgroundColor: '#2EC4B6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmSellerButtonText: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  loadingText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginTop: 16,
  },
  globalLoading: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },

  // Add these new styles to your existing styles object:

noSellersContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  padding: 32,
},
noSellersText: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
  marginTop: 16,
},
noSellersSubText: {
  fontSize: 14,
  color: '#CCCCCC',
  marginTop: 4,
  textAlign: 'center',
},

});
